
			<div class="container well">
				<div class="row">
					<div class="col-sm-12">
						<p>LEIA ATENTAMENTE A ESTE TERMO, POIS NELE ESTA CONTIDO TODAS AS REGRAS QUE NORTEIAM O USO DO AKIJOB</p>
						<h3>Aceitação dos termos.</h3>
						<p>Ao se registrar e/ou usar o Serviço de toda e qualquer forma, incluindo, mas não se limitando a, visitar ou utilizar o Site, você concorda com todos os termos e condições contidos aqui ("Termos de uso"), que também incorporam a Política de privacidade do AkiJob, políticas e procedimentos que podem ser publicados de tempos em tempos no Site pelo AkiJob, do qual cada um é incorporado por referência e pode ser atualizado pelo AkiJob de tempos em tempos, sem avisos, de acordo com os termos estabelecidos na seção "Modificação dos Termos de uso" abaixo. Alguns serviços oferecidos pelo Serviço podem estar sujeitos a termos e condições adicionais especificados pelo AkiJob de tempos em tempos; o uso de tais serviços está sujeito aos termos e condições adicionais, que são incorporadas nestes Termos de uso através desta referência. Estes Termos de uso se aplicam a todos os usuários do Serviço, incluindo, mas não se limitando a, usuários contribuidores de conteúdo, informação e outros materiais ou serviços no Site, usuários individuais do Serviço, estabelecimentos que acessam o Serviço e usuários que possuem uma página no Serviço.</p>
						<h3>Acesso.</h3>
						<p>Sujeito a estes Termos de Uso, o AkiJob pode oferecer o fornecimento dos Serviços, descritos com mais exatidão no site, e que são selecionados por você, somente para seu uso pessoal, e não para o uso ou benefício de qualquer terceiro. Os serviços devem incluir, mas não se limitar a, quaisquer serviços realizados para você pelo AkiJob, quaisquer aplicativos ou widgets oferecidos pelo AkiJob baixados do site ou, sujeito aos termos estabelecidos na seção "Sites e Serviços de terceiros" abaixo, de lojas de aplicativos de terceiros (ex: Play Store) autorizados pelo AkiJob, assim como o oferecimento de quaisquer materiais mostrados ou realizados pelos, ou através dos, Serviços (incluindo Conteúdo (como definido abaixo)).</p>
						<h3>Cadastro e elegibilidade.</h3>
						<p>Você pode navegar pelo Site e ver Conteúdo sem se cadastrar, mas, para usar certos aspectos do Serviço, você é obrigado a se cadastrar no AkiJob e agir, garantir e comprometer-se a fornecer ao AkiJob informações de cadastro exatas e completas (incluindo, mas não limitado a, seu nome de usuário ("Nome de usuário"), endereço de email e/ou número de telefone celular, e a senha que vai usar para acessar o Serviço) e a manter essas informações exatas e atualizadas. Deixar de fazer isto constituirá uma violação dos Termos de Uso, que pode resultar na rescisão imediata da sua conta no AkiJob. Recomendamos, mas não exigimos, que você use seu próprio nome como o Nome de usuário para que seus amigos possam reconhecê-lo com mais facilidade. Você não deve:
							<ul>
								<li>criar uma conta para ninguém além de você mesmo sem possuir a permissão de tal pessoa;</li>
								<li>usar um Nome de usuário que seja o nome de outra pessoa com a intenção de passar por essa pessoa;</li>
								<li>usar um Nome de usuário ou conta AkiJob que esteja sujeita a quaisquer direitos de uma pessoa que não seja você, sem a devida autorização; ou</li>
								<li>usar um Nome de usuário que seja um nome ofensivo, vulgar, obsceno ou ilegal.</li>
							</ul>
							O AkiJob reserva-se o direito de recusar o cadastro de, ou cancelar um Nome de usuário, a seu exclusivo critério. Você é o único responsável por atividades que ocorrem em sua conta e será responsável por manter a confidencialidade de sua senha do AkiJob. Você nunca deverá usar a conta de outro usuário sem sua autorização prévia. Você deverá notificar imediatamente por escrito ou por <i>email</i>(suporte@akijob.com.br - email ficticio) o AkiJob sobre qualquer uso não autorizado de sua conta, ou qualquer outra violação de segurança relacionada a uma conta de que você está ciente. Você declara e garante que, se você é pessoa física, você tem a idade legal para assinar um contrato vinculativo, ou que, se você está cadastrando em nome de uma entidade, está autorizado a entrar e vincular a entidade a estes Termos de Uso e se cadastrar no Serviço. O Serviço não está disponível para indivíduos com menos de 13 anos de idade. O AkiJob pode, a seu exclusivo critério, recusar-se a oferecer o Serviço a qualquer pessoa ou entidade e alterar seus critérios de elegibilidade a qualquer momento. Você é o único responsável por garantir que estes Termos de Uso estão em conformidade com todas as leis, normas e regulamentos aplicáveis ​​a você. O direito de acesso ao Serviço é revogado onde estes Termos de Uso ou utilização do Serviço são proibidos e, em tais circunstâncias, você concorda em não usar ou acessar o Site ou os Serviços de qualquer forma. Se você usar um aparelho móvel, esteja ciente de que as tarifas e taxas habituais de sua operadora, tais como cobranças de mensagens e dados, ainda serão aplicadas. Em caso de mudança ou desativação do número do seu telefone celular, você concorda que atualizará as informações de sua conta nos Serviços dentro de 48 horas para garantir que suas mensagens não sejam enviadas para a pessoa que adquirir o seu número anterior.	
						</p>
						<h3>Conteúdo.</h3>
						<p>Todo o Conteúdo, seja ele veiculado publicamente ou transmitido privativamente, é de exclusiva responsabilidade da pessoa que o originou. O AkiJob não pode garantir a autenticidade de qualquer Conteúdo ou dados que usuários fornecem sobre si mesmos. Você reconhece que todo o Conteúdo que acessar usando o Serviço será por sua conta e risco e você será o único responsável por qualquer dano ou perda decorrente para você ou qualquer outra parte. Para fins destes Termos de Uso, o termo "Conteúdo" inclui, sem limitação, qualquer informação sobre a localização, "gritos", vídeos, clipes de áudio, comentários, informações, dados, textos, fotografias, software, scripts, gráficos e recursos interativos gerados, fornecidos ou tornados acessíveis pelo AkiJob no, ou pelo Serviço. Conteúdo adicionado, criado, carregado, enviado, distribuído, publicado ou obtido pelo Serviço por usuários, incluindo Conteúdo adicionado ao Serviço ligado a usuários conectando suas contas a sites e serviços de terceiros, são coletivamente referidos como "Envios de Usuário".</p>
						<h3>Envios de Usuário.</h3>
						<p>Nós poderemos usar seus Envios de Usuário de diversas maneiras relacionadas ao Site, Serviços e negócios da AkiJob da maneira como a AkiJob determinar a seu exclusivo critério, incluindo, sem limitação, exibi-los publicamente, reformatando-os, incorporando-os em materiais de marketing, anúncios e outras obras, criando obras derivadas dos envios, promovendo-os, distribuindo-os e permitindo que outros usuários façam o mesmo em relação a seus próprios sites, plataformas de mídia e aplicativos (\"Mídia de terceiros\"). Ao enviar Envios de Usuário no Site ou pelo Serviço, você concede à AkiJob uma licença sublicenciável e transferível mundial, não exclusiva, livre de royalties e totalmente paga para usar, copiar, editar, modificar, reproduzir, distribuir, preparar obras derivadas, exibir, realizar e explorar totalmente os Envios de Usuário relacionados ao Site, Serviço e aos negócios da AkiJob (e seus sucessores e representantes), incluindo, sem limitação, a promoção e redistribuição de parte ou todo do Site (e suas obras derivadas) ou Serviço em qualquer formato de mídia e por meio de qualquer canal de mídia (incluindo, sem limitação, sites e feeds de terceiros). Você também concede a cada usuário do Site e/ou Serviço, incluindo Mídia de terceiros, uma licença não exclusiva para acessar seus Envios de Usuário pelo Site e Serviço e para usar, editar, modificar, reproduzir, distribuir, preparar obras derivadas, exibir e realizar esses Envios de Usuário em relação ao uso do Site, Serviço e Mídia de terceiros. Para ser mais transparente, esta licença concedida à AkiJob não afeta seus outros direitos de propriedade ou licença do(s) seu(s) Envio(s) de Usuário, incluindo o direito de conceder outras licenças ao material do(s) seu(s) Envio(s) de Usuário, a não ser que seja disposto de outra forma, por escrito, com a AkiJob. Você representa e garante ter todos os direitos para nos conceder essa licença sem infringir nem violar direitos de terceiros, incluindo, sem limitação, quaisquer direitos de privacidade, direitos de publicidade, direitos autorais, diretos contratuais ou qualquer outro direito proprietário ou de propriedade intelectual.Você entende que toda informação postada publicamente ou transmitida em privacidade pelo Site é de única responsabilidade da pessoa que originou o Conteúdo; que a AkiJob não será responsabilizada por quaisquer erros ou omissões de Conteúdo; e que a AkiJob não poderá garantir a identidade de quaisquer outros usuários com quem você possa interagir durante seu uso do Serviço.Quando você excluir Envios de Usuário, eles serão removidos do Serviço. Contudo, você entende que os Envios de Usuário removidos podem permanecer em cópias de backup por um período razoável (mas, tendo sido removidos, não serão compartilhados com outras pessoas) ou podem permanecer com usuários que tenham anteriormente acessado ou baixado seus Envios de Usuário.</p>
						<h3>Regras e conduta</h3>
						<p>Como condição de uso, você promete não usar o Serviço para qualquer finalidade que seja proibida por estes Termos de Uso. Você é responsável por todas as suas atividades em conexão com o Serviço. Além disso, você deve respeitar todas as leis e regulamentos locais, estaduais, nacionais e internacionais. A título de exemplo, e não como uma limitação, você não deve (e não deve permitir o mesmo a terceiros) (a) tomar qualquer ação ou (b) fazer upload, download, publicar, enviar, distribuir ou facilitar a distribuição de qualquer Conteúdo no, ou através do Serviço, incluindo, sem limitação, qualquer Envio de usuário, que:
							<ul>
								<li>você reconhece que seja falso, enganoso, mentiroso ou inexato;</li>
								<li>seja ilegal, ameaçador, abusivo, ofensivo, difamatório, calunioso, enganoso, fraudulento, invada a privacidade do outro, injurioso, obsceno, vulgar, pornográfico, ofensivo, profano, contém ou retrata a nudez, contenha ou retrate a atividade sexual, promova a intolerância, a discriminação ou violência, ou seja inadequada, conforme determinado pelo AkiJob a seu exclusivo critério;</li>
								<li>constitui publicidade não autorizada ou não solicitada, e-mail lixo ou em massa ("spam");</li>
								<li>contenha vírus de software ou qualquer outro código, arquivos, worms, bombas lógicas ou programas de computador que são concebidos ou destinados a interromper, inutilizar, danificar, limitar ou interferir com o bom funcionamento de qualquer software, hardware ou equipamento de telecomunicações ou para danificar ou obter acesso não autorizado a qualquer sistema, dados, senhas ou outras informações do AkiJob ou de terceiros;</li>
								<li>imita qualquer pessoa ou entidade, incluindo qualquer funcionário ou representante do AkiJob;</li>
								<li>inclui documentos de identificação ou informações financeiras confidenciais de uma pessoa; ou</li>
								<li>viola a Política de Privacidade e/ou qualquer uma das outras políticas e normas aqui incorporadas.</li>
							</ul>
							Se o Envio de usuário inclui uma fotografia, a Diretrizes de fotografia do AkiJob serão aplicadas. O AkiJob tem uma política de tolerância zero contra a pornografia infantil, e excluirá e denunciará às autoridades apropriadas qualquer usuário que publique ou distribua pornografia infantil. Você não deve (direta ou indiretamente):
							<ul>
								<li>realizar uma ação que imponham ou possa impor (conforme determinado pelo AkiJob de acordo com seu exclusivo critério) uma carga irracional ou desproporcionalmente grande para a infraestrutura do AkiJob (ou de seus provedores terceirizados);</li>
								<li>interferir ou tentar interferir no funcionamento adequado do Serviço ou atividades realizadas no Serviço;</li>
								<li>ignorar quaisquer medidas que possam ser usadas pelo AkiJob para evitar ou restringir acesso ao Serviço (ou a outras contas, sistemas de computador ou redes conectadas ao Serviço);</li>
								<li>executar qualquer resposta automática ou "spam" no Serviço;</li>
								<li>usar software, dispositivos ou outros processos manuais ou automáticos para realizar atos de "crawl" ou "spider" em qualquer página no Site;</li>
								<li>coletar ou extrair qualquer conteúdo do Serviço;</li>
								<li>modificar, adaptar, apropriar, reproduzir, distribuir, traduzir, criar obras derivadas ou adaptações, exibir publicamente, republicar, reapropriar, vender, comercializar ou de alguma forma explorar o Serviço ou Conteúdo do site (exceto Envios de usuário), exceto, como expressamente autorizado pelo AkiJob;</li>
								<li>decifrar, descompilar, desmontar, fazer engenharia reversa ou tentar obter qualquer código-fonte ou ideias ou algoritmos subjacentes de qualquer parte do Serviço (incluindo, sem limitação, qualquer aplicativo ou widget), exceto na medida limitada em que leis proíbem especificamente tal restrição;</li>
								<li>copiar, alugar, arrendar, distribuir ou transferir quaisquer direitos que você recebe aqui;</li>
								<li>realizar uma ação que viole as diretrizes e políticas do AkiJob.</li>
							</ul>
							O AkiJob não garante que qualquer Conteúdo ou o Envios de usuário (conforme definido acima) serão disponibilizados no site ou através do Serviço. O AkiJob não tem nenhuma obrigação de monitorar o site, Serviço, Conteúdo ou Envios de Usuário. Entretanto, o AkiJob se reserva o direito de (i) remover, suspender, editar ou modificar qualquer Conteúdo a seu exclusivo critério, incluindo, sem limitação, qualquer Envio de usuário a qualquer momento, sem aviso a você e por qualquer motivo (incluindo, mas não limitado a, no recebimento de reivindicações ou alegações de terceiros ou autoridades em relação a tal Conteúdo ou se o AkiJob considerar que você tenha violado estes Termos de Uso), ou sem qualquer justificativa, e (ii) remover, suspender ou bloquear qualquer Envio de usuário do Serviço. O AkiJob também se reserva o direito de acessar, ler, preservar e divulgar qualquer informação conforme o AkiJob acredita ser razoavelmente necessário para (i) satisfazer qualquer lei, regulamentação, processo legal ou solicitação governamental aplicável, (ii) fazer cumprir estes Termos de Uso, incluindo a investigação de possíveis violações do mesmo, (iii) detectar, impedir ou de outra forma discutir fraude, segurança ou questões técnicas, (iv) responder a pedidos de suporte do usuário ou (v) proteger os direitos, a propriedade ou a segurança do AkiJob, seus usuários e o público.
						</p>
								
					</div>
				</div>
			</div>
